name: dio_retry
description: A starting point for Dart libraries or applications.
version: 0.1.9-beta
homepage: https://github.com/umair13adil/dio_retry
author: umair13adil <mua@embrace-it.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  meta: ^1.1.7
  logging: ^0.11.3+2
  dio: ^3.0.3

dev_dependencies:
  pedantic: ^1.8.0+1
  test: ^1.9.1
